name: CI Workflow

on: [pull_request, push]

jobs:
  ci-work:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Test
        run: |
          ls
          pwd

      - name: Push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{secrets.DOCKER_NAME}}/fast_api:${{github.run_number}}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        id: trivy
        with:
          image-ref: ${{secrets.DOCKER_NAME}}/fast_api:${{github.run_number}}
          exit-code: '1'

      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: Nicolas-S-M/Repo_fast_api_priv
          token: ${{secrets.ACESS_TOKEN}}

      - name: Push Docker image
        if: steps.trivy.outputs.exit-code == '0'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_NAME}}/fast_api:${{github.run_number}}
          
      - name: Update values.yaml
        if: steps.trivy.outputs.exit-code == '0'
        run: |
          sed -i 's|repository:.*|repository: '${{secrets.DOCKER_NAME}}/fast_api:${{github.run_number}}'|' values.yaml

      - name: Commit and push changes
        if: steps.trivy.outputs.exit-code == '0'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add values.yaml
          git commit -m "Update image tag to ${{secrets.DOCKER_NAME}}/fast_api:${{github.run_number}}"
          git push origin master
